using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EquipItemComponent : MonoBehaviour
{
    [SerializeField] private Transform _helmetSlot;    // 勇擔쫑
    [SerializeField] private Transform _armorSlot;     // 쌸퉣쫑
    [SerializeField] private Transform _weaponSlot;    // 졺쐑쫗

    [SerializeField] private GameObject _basicHand;

    private GameObject _equipHelmetPrefab;
    private GameObject _equipArmorPrefab;
    private GameObject _equipWeaponPrefab;

    /// <summary>
    /// Start
    /// </summary>
    private void Start()
    {
        EquipItemManager.OnItemEquipped += EquipPlayerItem;   // 쮅첇쾉첇 천췾왆쮴챹 웒, 칭첇쮩 쮅첇쾉 천췾
        EquipItemManager.OnItemUnEquipped += UnEquipPlayerItem;   // 쮅첇쾉첇 천췾촍왆쮴챹 웒, 칭첇쮩 쮅첇쾉 천췾촍
    }

    /// <summary>
    /// 칭첇쮩 쮅첇쾉 천췾
    /// </summary>
    public void EquipPlayerItem(OnEquipItemChangedArgs args)
    {
        switch (args.ItemType)
        {
            case ItemType.Helmet:
                if (_equipHelmetPrefab != null)
                    Destroy(_equipHelmetPrefab);
                _equipHelmetPrefab = Instantiate(args.Prefab, _helmetSlot);
                break;

            case ItemType.Armor:
                if (_equipArmorPrefab != null)
                    Destroy(_equipArmorPrefab);
                _equipArmorPrefab = Instantiate(args.Prefab, _armorSlot);
                break;

            case ItemType.Weapon:
                if (_equipWeaponPrefab != null)
                    Destroy(_equipWeaponPrefab);
                _equipWeaponPrefab = Instantiate(args.Prefab, _weaponSlot);
                _basicHand.SetActive(false);
                GetComponent<AnimComponent>().
                    Change_AttackAnimType((AttackAnimType)Enum.Parse(typeof(AttackAnimType), args.AttackAnimType));
                break;
        }
    }

    /// <summary>
    /// 칭첇쮩 쮅첇쾉 천췾촍
    /// </summary>
    public void UnEquipPlayerItem(OnEquipItemChangedArgs args)
    {
        switch (args.ItemType)
        {
            case ItemType.Helmet:
                if (_equipHelmetPrefab != null)
                    Destroy(_equipHelmetPrefab);
                break;

            case ItemType.Armor:
                if (_equipArmorPrefab != null)
                    Destroy(_equipArmorPrefab);
                break;

            case ItemType.Weapon:
                if (_equipWeaponPrefab != null)
                    Destroy(_equipWeaponPrefab);
                _basicHand.SetActive(true);
                GetComponent<AnimComponent>().
                    Change_AttackAnimType((AttackAnimType)Enum.Parse(typeof(AttackAnimType), args.AttackAnimType));
                break;
        }
    }

    /// <summary>
    /// OnDestroy
    /// </summary>
    private void OnDestroy()
    {
        EquipItemManager.OnItemEquipped -= EquipPlayerItem;
        EquipItemManager.OnItemUnEquipped -= UnEquipPlayerItem;

    }
}
